In [1]:
import pandas as pd

customers = pd.read_csv("data/customers.csv")
projects = pd.read_csv("data/projects.csv")
milestones = pd.read_csv("data/milestones.csv")
costs = pd.read_csv("data/costs.csv")

In [2]:
milestones["planned_date"] = pd.to_datetime(
    milestones["planned_date"],
    errors="coerce"
)

milestones["actual_date"] = pd.to_datetime(
    milestones["actual_date"],
    errors="coerce"
)

In [3]:
projects.columns

Index(['id', 'customer_id', 'name', 'start_date', 'target_go_live_date',
       'status', 'budget_amount'],
      dtype='str')

In [4]:
milestones.columns

Index(['id', 'project_id', 'type', 'planned_date', 'actual_date', 'status'], dtype='str')

In [5]:
costs.columns

Index(['id', 'project_id', 'cost_date', 'category', 'amount', 'currency'], dtype='str')

In [6]:
customers.columns

Index(['id', 'name', 'country', 'segment'], dtype='str')

In [7]:
projects.groupby("status").size()

status
Blocked         2
Done            3
In Progress    13
Planned         2
dtype: int64

In [8]:
projects.groupby("status", dropna=False).size()

status
Blocked         2
Done            3
In Progress    13
Planned         2
dtype: int64

In [11]:
projects.groupby("status").size().sort_values(ascending=False)

status
In Progress    13
Done            3
Blocked         2
Planned         2
dtype: int64

In [12]:
projects_by_status = (
    projects
    .groupby("status")
    .size()
    .sort_values(ascending=False)
)

In [13]:
costs.groupby("project_id")["amount"].sum()

project_id
1     53500.0
2     39200.0
3     81200.0
4     56600.0
5     32600.0
6      3200.0
7     98000.0
8     48700.0
9     33200.0
10    40100.0
11    60400.0
12    42200.0
13    41400.0
14    52000.0
15    43300.0
16     2800.0
17    66800.0
18    49700.0
19    72000.0
20    40600.0
Name: amount, dtype: float64

In [16]:
costs_by_project = (
    costs
    .groupby("project_id")["amount"]
    .sum()
    .sort_values(ascending=False)
)

costs_by_project

project_id
7     98000.0
3     81200.0
19    72000.0
17    66800.0
11    60400.0
4     56600.0
1     53500.0
14    52000.0
18    49700.0
8     48700.0
15    43300.0
12    42200.0
13    41400.0
20    40600.0
10    40100.0
2     39200.0
9     33200.0
5     32600.0
6      3200.0
16     2800.0
Name: amount, dtype: float64

In [18]:
milestones["completed_late"] = (
    milestones["actual_date"] > milestones["planned_date"]
)
milestones[["completed_late", "actual_date", "planned_date"]]

    completed_late actual_date planned_date
0             True  2025-12-21   2025-12-19
1            False         NaT   2026-01-05
2            False         NaT   2026-01-20
3             True  2026-01-07   2026-01-05
4            False         NaT   2026-01-12
5            False         NaT   2026-01-26
6            False  2025-11-26   2025-11-26
7             True  2026-01-06   2026-01-05
8            False  2026-01-18   2026-01-18
9             True  2026-01-09   2026-01-07
10           False         NaT   2026-01-14
11           False         NaT   2026-01-28
12            True  2026-01-03   2026-01-02
13           False         NaT   2026-01-10
14           False         NaT   2026-01-24
15           False         NaT   2026-01-22
16           False         NaT   2026-01-29
17           False         NaT   2026-02-10
18            True  2025-12-18   2025-12-16
19           False         NaT   2026-01-08
20           False         NaT   2026-01-22
21            True  2026-01-06   2026-01-03
22           False         NaT   2026-01-09
23           False         NaT   2026-01-19
24           False  2025-12-29   2025-12-29
25           False         NaT   2026-01-10
26           False         NaT   2026-01-24
27            True  2026-01-10   2026-01-09
28           False         NaT   2026-01-16
29           False         NaT   2026-01-30
30           False  2025-12-01   2025-12-01
31            True  2026-01-11   2026-01-10
32           False  2026-01-22   2026-01-22
33            True  2026-01-08   2026-01-06
34           False         NaT   2026-01-13
35           False         NaT   2026-01-27
36            True  2025-12-26   2025-12-23
37           False         NaT   2026-01-12
38           False         NaT   2026-01-26
39            True  2026-01-06   2026-01-04
40           False         NaT   2026-01-11
41           False         NaT   2026-01-25
42            True  2026-01-04   2026-01-02
43           False         NaT   2026-01-10
44           False         NaT   2026-02-24
45           False         NaT   2026-01-25
46           False         NaT   2026-02-02
47           False         NaT   2026-02-18
48           False  2025-11-22   2025-11-22
49            True  2026-01-09   2026-01-07
50           False  2026-01-16   2026-01-16
51            True  2025-12-29   2025-12-27
52           False         NaT   2026-01-08
53           False         NaT   2026-01-21
54            True  2026-01-10   2026-01-08
55           False         NaT   2026-01-18
56           False         NaT   2026-01-29
57            True  2026-01-12   2026-01-11
58           False         NaT   2026-01-19
59           False         NaT   2026-02-02

In [25]:
completed_milestones = milestones[milestones["actual_date"].notna()]

completed_milestones

    id  project_id     type planned_date actual_date status  completed_late
0    1           1  Kickoff   2025-12-19  2025-12-21   Done            True
3    4           2  Kickoff   2026-01-05  2026-01-07   Done            True
6    7           3  Kickoff   2025-11-26  2025-11-26   Done           False
7    8           3      UAT   2026-01-05  2026-01-06   Done            True
8    9           3  Go-Live   2026-01-18  2026-01-18   Done           False
9   10           4  Kickoff   2026-01-07  2026-01-09   Done            True
12  13           5  Kickoff   2026-01-02  2026-01-03   Done            True
18  19           7  Kickoff   2025-12-16  2025-12-18   Done            True
21  22           8  Kickoff   2026-01-03  2026-01-06   Done            True
24  25           9  Kickoff   2025-12-29  2025-12-29   Done           False
27  28          10  Kickoff   2026-01-09  2026-01-10   Done            True
30  31          11  Kickoff   2025-12-01  2025-12-01   Done           False
31  32          11      UAT   2026-01-10  2026-01-11   Done            True
32  33          11  Go-Live   2026-01-22  2026-01-22   Done           False
33  34          12  Kickoff   2026-01-06  2026-01-08   Done            True
36  37          13  Kickoff   2025-12-23  2025-12-26   Done            True
39  40          14  Kickoff   2026-01-04  2026-01-06   Done            True
42  43          15  Kickoff   2026-01-02  2026-01-04   Done            True
48  49          17  Kickoff   2025-11-22  2025-11-22   Done           False
49  50          17      UAT   2026-01-07  2026-01-09   Done            True
50  51          17  Go-Live   2026-01-16  2026-01-16   Done           False
51  52          18  Kickoff   2025-12-27  2025-12-29   Done            True
54  55          19  Kickoff   2026-01-08  2026-01-10   Done            True
57  58          20  Kickoff   2026-01-11  2026-01-12   Done            True

In [26]:
completed_milestones.groupby("completed_late").size()

completed_late
False     7
True     17
dtype: int64

In [27]:
(completed_milestones["completed_late"] == True).sum()

(completed_milestones["completed_late"] == True).size()

TypeError: 'int' object is not callable