In [1]:
import pandas as pd

In [2]:
projects = pd.read_csv("data/projects.csv")

In [3]:
type(projects)

pandas.DataFrame

In [4]:
projects.head()

,id,customer_id,name,start_date,target_go_live_date,status,budget_amount
0,1,1,Core Rollout,2025-12-18,2026-02-10,In Progress,60000.0
1,2,1,Portal Launch,2026-01-04,2026-03-01,In Progress,45000.0
2,3,2,POS Upgrade,2025-11-25,2026-01-20,Done,90000.0
3,4,2,Loyalty Setup,2026-01-06,2026-03-10,In Progress,70000.0
4,5,3,Supplier Hub,2025-12-30,2026-02-20,In Progress,33000.0

In [5]:
projects.head(10)

,id,customer_id,name,start_date,target_go_live_date,status,budget_amount
0,1,1,Core Rollout,2025-12-18,2026-02-10,In Progress,60000.0
1,2,1,Portal Launch,2026-01-04,2026-03-01,In Progress,45000.0
2,3,2,POS Upgrade,2025-11-25,2026-01-20,Done,90000.0
3,4,2,Loyalty Setup,2026-01-06,2026-03-10,In Progress,70000.0
4,5,3,Supplier Hub,2025-12-30,2026-02-20,In Progress,33000.0
5,6,3,Reporting Setup,2026-01-12,2026-03-05,Planned,25000.0
6,7,4,Workflow Upgrade,2025-12-15,2026-02-12,In Progress,80000.0
7,8,4,CRM Integration,2026-01-02,2026-03-15,In Progress,70000.0
8,9,5,Scheduling Deployment,2025-12-28,2026-02-28,Blocked,50000.0
9,10,5,Asset Dashboard,2026-01-08,2026-03-20,In Progress,41000.0

In [6]:
projects.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   20 non-null     int64
 1   customer_id          20 non-null     int64
 2   name                 20 non-null     str
 3   start_date           20 non-null     str
 4   target_go_live_date  20 non-null     str
 5   status               20 non-null     str
 6   budget_amount        20 non-null     float64
dtypes: float64(1), int64(2), str(4)
memory usage: 1.2 KB

In [7]:
projects.columns

Index(['id', 'customer_id', 'name', 'start_date', 'target_go_live_date',
       'status', 'budget_amount'],
      dtype='str')

In [8]:
projects.head

<bound method NDFrame.head of     id  customer_id                   name  start_date target_go_live_date  \
0    1            1           Core Rollout  2025-12-18          2026-02-10
1    2            1          Portal Launch  2026-01-04          2026-03-01
2    3            2            POS Upgrade  2025-11-25          2026-01-20
3    4            2          Loyalty Setup  2026-01-06          2026-03-10
4    5            3           Supplier Hub  2025-12-30          2026-02-20
5    6            3        Reporting Setup  2026-01-12          2026-03-05
6    7            4       Workflow Upgrade  2025-12-15          2026-02-12
7    8            4        CRM Integration  2026-01-02          2026-03-15
8    9            5  Scheduling Deployment  2025-12-28          2026-02-28
9   10            5        Asset Dashboard  2026-01-08          2026-03-20
10  11            6    Intake Digitization  2025-11-30          2026-01-25
11  12            6        Lab Integration  2026-01-05          2026-03-08
12  13            7  Checkout Optimization  2025-12-22          2026-02-18
13  14            7     Returns Automation  2026-01-03          2026-03-02
14  15            8     Maintenance Portal  2026-01-01          2026-02-25
15  16            8        Onboarding Flow  2026-01-18          2026-03-25
16  17            9   Cost Control Rollout  2025-11-20          2026-01-18
17  18            9         Site Reporting  2025-12-26          2026-02-22
18  19            9          Vendor Portal  2026-01-07          2026-03-12
19  20            9  Utilization Dashboard  2026-01-10          2026-03-18

         status  budget_amount
0   In Progress        60000.0
1   In Progress        45000.0
2          Done        90000.0
3   In Progress        70000.0
4   In Progress        33000.0
5       Planned        25000.0
6   In Progress        80000.0
7   In Progress        70000.0
8       Blocked        50000.0
9   In Progress        41000.0
10         Done        65000.0
11  In Progress        55000.0
12  In Progress        48000.0
13      Blocked        45000.0
14  In Progress        55000.0
15      Planned        38000.0
16         Done        72000.0
17  In Progress        60000.0
18  In Progress        60000.0
19  In Progress        52000.0  >

In [9]:
projects["status"]

0     In Progress
1     In Progress
2            Done
3     In Progress
4     In Progress
5         Planned
6     In Progress
7     In Progress
8         Blocked
9     In Progress
10           Done
11    In Progress
12    In Progress
13        Blocked
14    In Progress
15        Planned
16           Done
17    In Progress
18    In Progress
19    In Progress
Name: status, dtype: str

In [11]:
projects[["id", "status", "budget_amount"]]

    id       status  budget_amount
0    1  In Progress        60000.0
1    2  In Progress        45000.0
2    3         Done        90000.0
3    4  In Progress        70000.0
4    5  In Progress        33000.0
5    6      Planned        25000.0
6    7  In Progress        80000.0
7    8  In Progress        70000.0
8    9      Blocked        50000.0
9   10  In Progress        41000.0
10  11         Done        65000.0
11  12  In Progress        55000.0
12  13  In Progress        48000.0
13  14      Blocked        45000.0
14  15  In Progress        55000.0
15  16      Planned        38000.0
16  17         Done        72000.0
17  18  In Progress        60000.0
18  19  In Progress        60000.0
19  20  In Progress        52000.0

In [12]:
projects["status"] == "In Progress"

0      True
1      True
2     False
3      True
4      True
5     False
6      True
7      True
8     False
9      True
10    False
11     True
12     True
13    False
14     True
15    False
16    False
17     True
18     True
19     True
Name: status, dtype: bool

In [13]:
active_projects = projects[projects["status"] == "In Progress"]

In [14]:
print(active_projects)

    id  customer_id                   name  start_date target_go_live_date  \
0    1            1           Core Rollout  2025-12-18          2026-02-10
1    2            1          Portal Launch  2026-01-04          2026-03-01
3    4            2          Loyalty Setup  2026-01-06          2026-03-10
4    5            3           Supplier Hub  2025-12-30          2026-02-20
6    7            4       Workflow Upgrade  2025-12-15          2026-02-12
7    8            4        CRM Integration  2026-01-02          2026-03-15
9   10            5        Asset Dashboard  2026-01-08          2026-03-20
11  12            6        Lab Integration  2026-01-05          2026-03-08
12  13            7  Checkout Optimization  2025-12-22          2026-02-18
14  15            8     Maintenance Portal  2026-01-01          2026-02-25
17  18            9         Site Reporting  2025-12-26          2026-02-22
18  19            9          Vendor Portal  2026-01-07          2026-03-12
19  20            9  Utilization Dashboard  2026-01-10          2026-03-18

         status  budget_amount
0   In Progress        60000.0
1   In Progress        45000.0
3   In Progress        70000.0
4   In Progress        33000.0
6   In Progress        80000.0
7   In Progress        70000.0
9   In Progress        41000.0
11  In Progress        55000.0
12  In Progress        48000.0
14  In Progress        55000.0
17  In Progress        60000.0
18  In Progress        60000.0
19  In Progress        52000.0

In [15]:
projects["id"]

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
12    13
13    14
14    15
15    16
16    17
17    18
18    19
19    20
Name: id, dtype: int64

In [19]:
d = projects["budget_amount"] > 50000

In [20]:
projects[d]

,id,customer_id,name,start_date,target_go_live_date,status,budget_amount
0,1,1,Core Rollout,2025-12-18,2026-02-10,In Progress,60000.0
2,3,2,POS Upgrade,2025-11-25,2026-01-20,Done,90000.0
3,4,2,Loyalty Setup,2026-01-06,2026-03-10,In Progress,70000.0
6,7,4,Workflow Upgrade,2025-12-15,2026-02-12,In Progress,80000.0
7,8,4,CRM Integration,2026-01-02,2026-03-15,In Progress,70000.0
10,11,6,Intake Digitization,2025-11-30,2026-01-25,Done,65000.0
11,12,6,Lab Integration,2026-01-05,2026-03-08,In Progress,55000.0
14,15,8,Maintenance Portal,2026-01-01,2026-02-25,In Progress,55000.0
16,17,9,Cost Control Rollout,2025-11-20,2026-01-18,Done,72000.0
17,18,9,Site Reporting,2025-12-26,2026-02-22,In Progress,60000.0
18,19,9,Vendor Portal,2026-01-07,2026-03-12,In Progress,60000.0
19,20,9,Utilization Dashboard,2026-01-10,2026-03-18,In Progress,52000.0

In [23]:
projects[projects["status"] == "In Progress"][["id", "status"]]

    id       status
0    1  In Progress
1    2  In Progress
3    4  In Progress
4    5  In Progress
6    7  In Progress
7    8  In Progress
9   10  In Progress
11  12  In Progress
12  13  In Progress
14  15  In Progress
17  18  In Progress
18  19  In Progress
19  20  In Progress

In [25]:
milestones = pd.read_csv("data/milestones.csv")
customers = pd.read_csv("data/customers.csv")
costs = pd.read_csv("data/costs.csv")

In [26]:
milestones.info()

<class 'pandas.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            60 non-null     int64
 1   project_id    60 non-null     int64
 2   type          60 non-null     str
 3   planned_date  60 non-null     str
 4   actual_date   24 non-null     str
 5   status        60 non-null     str
dtypes: int64(2), str(4)
memory usage: 2.9 KB

In [27]:
milestones.head()

   id  project_id       type planned_date actual_date       status
0   1           1    Kickoff   2025-12-19  2025-12-21         Done
1   2           1  Discovery   2026-01-05         NaN  In Progress
2   3           1      Build   2026-01-20         NaN      Planned
3   4           2    Kickoff   2026-01-05  2026-01-07         Done
4   5           2  Discovery   2026-01-12         NaN  In Progress

In [28]:
costs.head()

   id  project_id   cost_date  category   amount currency
0   1           1  2025-12-20    Vendor  14000.0      EUR
1   2           1  2026-01-05  Internal  12000.0      EUR
2   3           1  2026-01-12     Infra   8500.0      EUR
3   4           1  2026-01-17   Support   6000.0      EUR
4   5           1  2026-01-19    Travel   1500.0      EUR

In [29]:
costs.info()

<class 'pandas.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          120 non-null    int64
 1   project_id  120 non-null    int64
 2   cost_date   120 non-null    str
 3   category    120 non-null    str
 4   amount      120 non-null    float64
 5   currency    120 non-null    str
dtypes: float64(1), int64(2), str(3)
memory usage: 5.8 KB