In [30]:
import pandas as pd

In [31]:
projects = pd.read_csv("../data/projects.csv")
customers = pd.read_csv("../data/customers.csv")
milestones = pd.read_csv("../data/milestones.csv")
costs = pd.read_csv("../data/costs.csv")

In [32]:
projects_with_customers = projects.merge(customers, left_on="customer_id", right_on="id", how="left")

In [33]:
projects_with_customers.head()

,id_x,customer_id,name_x,start_date,target_go_live_date,status,budget_amount,id_y,name_y,country,segment
0,1,1,Core Rollout,2025-12-18,2026-02-10,In Progress,60000.0,1,Acme Logistics,DE,Mid-Market
1,2,1,Portal Launch,2026-01-04,2026-03-01,In Progress,45000.0,1,Acme Logistics,DE,Mid-Market
2,3,2,POS Upgrade,2025-11-25,2026-01-20,Done,90000.0,2,Nordic Retail Group,DK,Enterprise
3,4,2,Loyalty Setup,2026-01-06,2026-03-10,In Progress,70000.0,2,Nordic Retail Group,DK,Enterprise
4,5,3,Supplier Hub,2025-12-30,2026-02-20,In Progress,33000.0,3,BluePeak Manufacturing,PL,SMB

In [34]:
projects_with_customers = projects.merge(customers, left_on="customer_id", right_on="id", how="left", suffixes=("_projects", "_customers"))

In [35]:
projects_with_customers[["name_projects", "name_customers", "status"]].head()

   name_projects          name_customers       status
0   Core Rollout          Acme Logistics  In Progress
1  Portal Launch          Acme Logistics  In Progress
2    POS Upgrade     Nordic Retail Group         Done
3  Loyalty Setup     Nordic Retail Group  In Progress
4   Supplier Hub  BluePeak Manufacturing  In Progress

In [36]:
projects_with_customers = projects.merge(
    customers,
    left_on="customer_id",
    right_on="id",
    how="left",
    suffixes=("_projects", "_customers"),
    validate="many_to_one"
)
projects_with_customers.head()

,id_projects,customer_id,name_projects,start_date,target_go_live_date,status,budget_amount,id_customers,name_customers,country,segment
0,1,1,Core Rollout,2025-12-18,2026-02-10,In Progress,60000.0,1,Acme Logistics,DE,Mid-Market
1,2,1,Portal Launch,2026-01-04,2026-03-01,In Progress,45000.0,1,Acme Logistics,DE,Mid-Market
2,3,2,POS Upgrade,2025-11-25,2026-01-20,Done,90000.0,2,Nordic Retail Group,DK,Enterprise
3,4,2,Loyalty Setup,2026-01-06,2026-03-10,In Progress,70000.0,2,Nordic Retail Group,DK,Enterprise
4,5,3,Supplier Hub,2025-12-30,2026-02-20,In Progress,33000.0,3,BluePeak Manufacturing,PL,SMB

In [37]:
len(projects)

20

In [38]:
len(projects_with_customers)

20

In [39]:
projects_with_milestones = projects.merge(milestones, left_on="id", right_on="project_id", how="left", validate="one_to_many")

In [40]:
len(projects)

20

In [41]:
len(projects_with_milestones)

60

In [42]:
len(costs)

120

In [43]:
costs_with_milestones = costs.merge(milestones[["project_id", "type"]], on="project_id", how="left")

In [44]:
len(costs_with_milestones)

360

In [45]:
original_cost = costs["amount"].sum()
original_cost

np.float64(957500.0)

In [46]:
fanout_cost = costs_with_milestones["amount"].sum()
fanout_cost

np.float64(2872500.0)