In [1]:
import pandas as pd

customers = pd.read_csv("data/customers.csv")
projects = pd.read_csv("data/projects.csv")
milestones = pd.read_csv("data/milestones.csv")
costs = pd.read_csv("data/costs.csv")

In [2]:
projects.head()

,id,customer_id,name,start_date,target_go_live_date,status,budget_amount
0,1,1,Core Rollout,2025-12-18,2026-02-10,In Progress,60000.0
1,2,1,Portal Launch,2026-01-04,2026-03-01,In Progress,45000.0
2,3,2,POS Upgrade,2025-11-25,2026-01-20,Done,90000.0
3,4,2,Loyalty Setup,2026-01-06,2026-03-10,In Progress,70000.0
4,5,3,Supplier Hub,2025-12-30,2026-02-20,In Progress,33000.0

In [3]:
projects.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   20 non-null     int64
 1   customer_id          20 non-null     int64
 2   name                 20 non-null     str
 3   start_date           20 non-null     str
 4   target_go_live_date  20 non-null     str
 5   status               20 non-null     str
 6   budget_amount        20 non-null     float64
dtypes: float64(1), int64(2), str(4)
memory usage: 1.2 KB

In [4]:
projects.dtypes

id                       int64
customer_id              int64
name                       str
start_date                 str
target_go_live_date        str
status                     str
budget_amount          float64
dtype: object

In [5]:
projects.isna()

,id,customer_id,name,start_date,target_go_live_date,status,budget_amount
0,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False

In [6]:
projects.isna().sum()

id                     0
customer_id            0
name                   0
start_date             0
target_go_live_date    0
status                 0
budget_amount          0
dtype: int64

In [7]:
customers.isna().sum()

id         0
name       0
country    0
segment    0
dtype: int64

In [10]:
milestones.isna().sum()

id               0
project_id       0
type             0
planned_date     0
actual_date     36
status           0
dtype: int64

In [11]:
costs.isna().sum()

id            0
project_id    0
cost_date     0
category      0
amount        0
currency      0
dtype: int64

In [12]:
projects.columns

Index(['id', 'customer_id', 'name', 'start_date', 'target_go_live_date',
       'status', 'budget_amount'],
      dtype='str')

In [13]:
milestones.columns

Index(['id', 'project_id', 'type', 'planned_date', 'actual_date', 'status'], dtype='str')

In [14]:
milestones["actual_date"].dtype

In [15]:
milestones["actual_date"] = pd.to_datetime(
    milestones["actual_date"],
    errors="coerce"
)

In [16]:
milestones["actual_date"].dtype

dtype('<M8[us]')

In [17]:
cutoff_date = pd.to_datetime("2026-09-17")

In [18]:
milestones[milestones["actual_date"] < cutoff_date]

    id  project_id     type planned_date actual_date status
0    1           1  Kickoff   2025-12-19  2025-12-21   Done
3    4           2  Kickoff   2026-01-05  2026-01-07   Done
6    7           3  Kickoff   2025-11-26  2025-11-26   Done
7    8           3      UAT   2026-01-05  2026-01-06   Done
8    9           3  Go-Live   2026-01-18  2026-01-18   Done
9   10           4  Kickoff   2026-01-07  2026-01-09   Done
12  13           5  Kickoff   2026-01-02  2026-01-03   Done
18  19           7  Kickoff   2025-12-16  2025-12-18   Done
21  22           8  Kickoff   2026-01-03  2026-01-06   Done
24  25           9  Kickoff   2025-12-29  2025-12-29   Done
27  28          10  Kickoff   2026-01-09  2026-01-10   Done
30  31          11  Kickoff   2025-12-01  2025-12-01   Done
31  32          11      UAT   2026-01-10  2026-01-11   Done
32  33          11  Go-Live   2026-01-22  2026-01-22   Done
33  34          12  Kickoff   2026-01-06  2026-01-08   Done
36  37          13  Kickoff   2025-12-23  2025-12-26   Done
39  40          14  Kickoff   2026-01-04  2026-01-06   Done
42  43          15  Kickoff   2026-01-02  2026-01-04   Done
48  49          17  Kickoff   2025-11-22  2025-11-22   Done
49  50          17      UAT   2026-01-07  2026-01-09   Done
50  51          17  Go-Live   2026-01-16  2026-01-16   Done
51  52          18  Kickoff   2025-12-27  2025-12-29   Done
54  55          19  Kickoff   2026-01-08  2026-01-10   Done
57  58          20  Kickoff   2026-01-11  2026-01-12   Done

In [19]:
milestones["actual_date"]

0    2025-12-21
1           NaT
2           NaT
3    2026-01-07
4           NaT
5           NaT
6    2025-11-26
7    2026-01-06
8    2026-01-18
9    2026-01-09
10          NaT
11          NaT
12   2026-01-03
13          NaT
14          NaT
15          NaT
16          NaT
17          NaT
18   2025-12-18
19          NaT
20          NaT
21   2026-01-06
22          NaT
23          NaT
24   2025-12-29
25          NaT
26          NaT
27   2026-01-10
28          NaT
29          NaT
30   2025-12-01
31   2026-01-11
32   2026-01-22
33   2026-01-08
34          NaT
35          NaT
36   2025-12-26
37          NaT
38          NaT
39   2026-01-06
40          NaT
41          NaT
42   2026-01-04
43          NaT
44          NaT
45          NaT
46          NaT
47          NaT
48   2025-11-22
49   2026-01-09
50   2026-01-16
51   2025-12-29
52          NaT
53          NaT
54   2026-01-10
55          NaT
56          NaT
57   2026-01-12
58          NaT
59          NaT
Name: actual_date, dtype: datetime64[us]

In [20]:
milestones[milestones["actual_date"].isna()]

    id  project_id         type planned_date actual_date       status
1    2           1    Discovery   2026-01-05         NaT  In Progress
2    3           1        Build   2026-01-20         NaT      Planned
4    5           2    Discovery   2026-01-12         NaT  In Progress
5    6           2  Integration   2026-01-26         NaT      Planned
10  11           4    Discovery   2026-01-14         NaT  In Progress
11  12           4        Build   2026-01-28         NaT      Planned
13  14           5    Discovery   2026-01-10         NaT  In Progress
14  15           5  Integration   2026-01-24         NaT      Planned
15  16           6      Kickoff   2026-01-22         NaT      Planned
16  17           6    Discovery   2026-01-29         NaT      Planned
17  18           6        Build   2026-02-10         NaT      Planned
19  20           7  Integration   2026-01-08         NaT  In Progress
20  21           7          UAT   2026-01-22         NaT      Planned
22  23           8    Discovery   2026-01-09         NaT  In Progress
23  24           8          UAT   2026-01-19         NaT  In Progress
25  26           9    Discovery   2026-01-10         NaT      Blocked
26  27           9        Build   2026-01-24         NaT      Planned
28  29          10    Discovery   2026-01-16         NaT  In Progress
29  30          10  Integration   2026-01-30         NaT      Planned
34  35          12    Discovery   2026-01-13         NaT  In Progress
35  36          12        Build   2026-01-27         NaT      Planned
37  38          13  Integration   2026-01-12         NaT  In Progress
38  39          13          UAT   2026-01-26         NaT      Planned
40  41          14    Discovery   2026-01-11         NaT      Blocked
41  42          14        Build   2026-01-25         NaT      Planned
43  44          15    Discovery   2026-01-10         NaT  In Progress
44  45          15      Go-Live   2026-02-24         NaT      Planned
45  46          16      Kickoff   2026-01-25         NaT      Planned
46  47          16    Discovery   2026-02-02         NaT      Planned
47  48          16  Integration   2026-02-18         NaT      Planned
52  53          18    Discovery   2026-01-08         NaT  In Progress
53  54          18  Integration   2026-01-21         NaT  In Progress
55  56          19        Build   2026-01-18         NaT  In Progress
56  57          19          UAT   2026-01-29         NaT      Planned
58  59          20    Discovery   2026-01-19         NaT  In Progress
59  60          20        Build   2026-02-02         NaT      Planned

In [23]:
milestones["planned_date"] = pd.to_datetime(
    milestones["planned_date"],
    errors="coerce"
)

In [24]:
milestones[
    (milestones["planned_date"] < cutoff_date)
    &
    (milestones["actual_date"].isna())
]

    id  project_id         type planned_date actual_date       status
1    2           1    Discovery   2026-01-05         NaT  In Progress
2    3           1        Build   2026-01-20         NaT      Planned
4    5           2    Discovery   2026-01-12         NaT  In Progress
5    6           2  Integration   2026-01-26         NaT      Planned
10  11           4    Discovery   2026-01-14         NaT  In Progress
11  12           4        Build   2026-01-28         NaT      Planned
13  14           5    Discovery   2026-01-10         NaT  In Progress
14  15           5  Integration   2026-01-24         NaT      Planned
15  16           6      Kickoff   2026-01-22         NaT      Planned
16  17           6    Discovery   2026-01-29         NaT      Planned
17  18           6        Build   2026-02-10         NaT      Planned
19  20           7  Integration   2026-01-08         NaT  In Progress
20  21           7          UAT   2026-01-22         NaT      Planned
22  23           8    Discovery   2026-01-09         NaT  In Progress
23  24           8          UAT   2026-01-19         NaT  In Progress
25  26           9    Discovery   2026-01-10         NaT      Blocked
26  27           9        Build   2026-01-24         NaT      Planned
28  29          10    Discovery   2026-01-16         NaT  In Progress
29  30          10  Integration   2026-01-30         NaT      Planned
34  35          12    Discovery   2026-01-13         NaT  In Progress
35  36          12        Build   2026-01-27         NaT      Planned
37  38          13  Integration   2026-01-12         NaT  In Progress
38  39          13          UAT   2026-01-26         NaT      Planned
40  41          14    Discovery   2026-01-11         NaT      Blocked
41  42          14        Build   2026-01-25         NaT      Planned
43  44          15    Discovery   2026-01-10         NaT  In Progress
44  45          15      Go-Live   2026-02-24         NaT      Planned
45  46          16      Kickoff   2026-01-25         NaT      Planned
46  47          16    Discovery   2026-02-02         NaT      Planned
47  48          16  Integration   2026-02-18         NaT      Planned
52  53          18    Discovery   2026-01-08         NaT  In Progress
53  54          18  Integration   2026-01-21         NaT  In Progress
55  56          19        Build   2026-01-18         NaT  In Progress
56  57          19          UAT   2026-01-29         NaT      Planned
58  59          20    Discovery   2026-01-19         NaT  In Progress
59  60          20        Build   2026-02-02         NaT      Planned

In [25]:
milestones["actual_date"].isna().sum()

np.int64(36)